### ISSUE TITLE
where is the ".vim_runtime"  directory?

### ISSUE THREAD

**Issue by LingLingAngle** [kiddlu/oh-my-config#1]
hi, 
        I have synced your config project and I found that  "source ~/.vim_runtime/vimrcs/basic.vim" is in your .vimrc .  
        But there is none directory named ".vim_runtime" in your project.

**Comment by kiddlu** [comment]
Hi,

I use amix vimrc for runtime

git clone https://github.com/amix/vimrc.git ~/.vim_runtime

**Comment by LingLingAngle** [comment]
ok, I see it.  Thanks
